package com.basis.documents.domain;

public enum ReconciliationClass {
    EXACT_MATCH, EQUIVALENT_AFTER_NORMALIZATION, PERIOD_MISMATCH, UNIT_MISMATCH,
    AMENDED_VALUE, MISSING_VALUE, CONFLICTING_VALUE, LOW_CONFIDENCE_MATCH, UNSUPPORTED_COMPARISON
}
